### ISSUE TITLE
FORMATO DA DATA

### ISSUE THREAD

**Issue by juditecypreste** [htadashi/CalculadoraCidadao.gs#1]
olá! 
Eu fiz a instalação como recomendando, mas o formato da data não está exposto e não sei se está dando erro por causa disso. Qual seria o formato correto?

**Comment by htadashi** [comment]
Olá Judite, obrigado pelo interesse no nosso script! Realmente, este é um ponto que causa muita confusão. 

Há duas maneiras de usar as nossas fórmulas no GoogleSheets. 
1. A primeira é referenciando as células que contém as datas, e nesse caso basta usar nessas células qualquer data que normalmente tenha a conversão automática pelo GoogleSheets para o formato de data.
2. A segunda é usando a data diretamente na fórmula. Nesse caso deve-se utilizar a função [`DATE`](https://support.google.com/docs/answer/3092969?hl=en&ref_topic=3105385) para que o script entenda o valor como uma  data. Por exemplo, a fórmula `=CORRIGIR_SELIC(DATE(2021; 1; 1);DATE(2021; 9; 1);100)` vai usar a data inicial de 1/1/2021 e a data final de 1/9/2021.
