### ISSUE TITLE
TypeError: Cannot read property '1' of null (linha 18).

### ISSUE THREAD

**Issue by rafaellopes** [htadashi/CalculadoraCidadao.gs#3]
Olá htdadash,
Parabéns pela iniciativa!
Tentei usar, mas independente do índice que utilizo ele sempre apresenta esse erro na linha 18.

Fórmula:
=CORRIGIR_INDICE_DE_PRECO(A3;D2;C3;"IGP-M")

Erro apresentado:
TypeError: Cannot read property '1' of null (linha 18).

**Comment by htadashi** [comment]
Olá @rafaellopes , não consegui reproduzir o erro.
Teria como compartilhar uma planilha de teste para eu dar uma olhada?

**Comment by rafaellopes** [comment]
Claro
https://docs.google.com/spreadsheets/d/1SvzxawCc3CfWacedfUH18S-OxPq1aLmYgh5T8mItT1M/edit?usp=sharing

**Comment by htadashi** [comment]
@rafaellopes 
Entendi o erro. É que a própria [calculadora do BACEN](https://www3.bcb.gov.br/CALCIDADAO/publico/corrigirPorIndice.do?method=corrigirPorIndice) não tem o índice IGP-M disponível do mês atual: o mais recente é do mês anterior.

Se você usar a data final como 31/10/2021 daria certo, mas não 01/11/2021.
