### ISSUE TITLE
Erro na função CORRIGIR_INDICE_DE_PRECO

### ISSUE THREAD

**Issue by jpcruz6000** [htadashi/CalculadoraCidadao.gs#5]
Olá amigo, fui testar e aqui deu erro na função CORRIGIR_INDICE_DE_PRECO.
   
Exemplo =CORRIGIR_INDICE_DE_PRECO(A2;B2;C2;'IGP-M')

#ERRO! indice_de_preco inválido.

**Comment by htadashi** [comment]
Olá @jpcruz6000. Aparentemente, o site da calculadora cidadão está fora do ar no momento :( 
Caso voltar ao ar, poderia abrir novamente a issue com uma planilha para reproduzirmos o erro?

Abraços
