### ISSUE TITLE
TypeError: Cannot read property '1' of null parseResponse	@ CalculadoraCidadao.gs.gs:18

### ISSUE THREAD

**Issue by rafaellopes** [htadashi/CalculadoraCidadao.gs#6]
Olá pessoal, boa tarde.
Sou um fã desse projeto. Tem um potencial enorme de aplicações, mas vejo poucas pessoas utilizando. Uma pena.
Recentemente o script parou de funcionar. Vide anexo.
Alguém sabe me dizer o que está acontecendo? E como faço para resolver?
<img width="858" alt="Captura de Tela 2022-01-24 às 19 00 07" src="https://user-images.githubusercontent.com/567036/150847259-b024b376-2f18-45d4-be58-0f3e9b06ad41.png">

**Comment by jpcruz6000** [comment]
> Olá pessoal, boa tarde. Sou um fã desse projeto. Tem um potencial enorme de aplicações, mas vejo poucas pessoas utilizando. Uma pena. Recentemente o script parou de funcionar. Vide anexo. Alguém sabe me dizer o que está acontecendo? E como faço para resolver? <img alt="Captura de Tela 2022-01-24 às 19 00 07" width="858" src="https://user-images.githubusercontent.com/567036/150847259-b024b376-2f18-45d4-be58-0f3e9b06ad41.png">

Olá Raffael!  O site do banco central está fora do ar, tente mais tarde quando o site voltar a funcionar.

**Comment by rafaellopes** [comment]
Obrigado!



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
25/01/22
16:45:31

**Comment by htadashi** [comment]
Olá @rafaellopes e @jpcruz6000, obrigado. Ficamos felizes em saber que nossa planilha está sendo útil para vocês.

Atualizei o script para mostrar uma mensagem de erro caso a conexão com o BCB esteja falhando:
![image](https://user-images.githubusercontent.com/2355491/151703103-109ccbba-8166-4e9e-b3cb-f183db680498.png)
