### ISSUE TITLE
Error: conexão com site do BCB com problemas (line 51).

### ISSUE THREAD

**Issue by esimioni** [htadashi/CalculadoraCidadao.gs#8]
Olá!

Tenho algumas planilhas utilizando o código de vocês, o que facilita muito minha vida!
Todos os meses insiro uma nova linha em algumas delas, e nunca tive problemas, porém hoje começou a apresentar este erro, apenas na linha nova (utilizando a mesma fórmula das demais):

Error: conexão com site do BCB com problemas (line 51).

Fiz o cálculo no site do BCB na mão e funcionou.

**Comment by esimioni** [comment]
Removi a fórmula da célula e readicionei a mesma fórmula e funcionou 🧐🤔

**Comment by htadashi** [comment]
Obrigado por relatar o problema e por sugerir uma solução. O erro pode surgir devido à limitação na frequência das requisições pelo servidor do Google Sheets, o que impede o envio da requisição para o BCB.

**Comment by esimioni** [comment]
Hoje o problema está acontecendo novamente, e desta vez nem a solução acima não está funcionando.

**Comment by esimioni** [comment]
Hoje mexi na planilha novamente e descobri o problema e solução.
Se eu colocar a atualização pelo CDI até a data de ontem, sendo ontem dia útil, e hoje antes das 12h, o erro do título desta issue aparecerá. Aparentemente o BCB disponibiliza este índice apenas após as 12h do dia posterior.

Provavelmente ao fazer direto no site do BCB seria exibida uma mensagem que a correção pelo índice não está disponível nas datas selecionadas. Não sei se seria possível capturar esta mensagem de erro e exibí-la ao invés do erro genérico.

**Comment by htadashi** [comment]
@esimioni Boa ideia! A sugestão foi implementada no PR https://github.com/htadashi/CalculadoraCidadao.gs/pull/9 e em breve a feature será lançada em nova versão.
